apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-configmap
data:
  index.html: |
    <!DOCTYPE html> 
    <html>
        <head>
            <title>Kubernetes practice</title>
        </head>
        <body>
            <h1>Hello, config-map</h1>
            <p>I'm working</p>
        </body> 
    </html>
